MODULE INTERFACE
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE BASIS(STATE,BASIS_DIM,NP,NS)
       USE LATTICE
       IMPLICIT NONE
       INTEGER, DIMENSION(:,:), INTENT(OUT) :: STATE
       INTEGER, INTENT(IN) :: BASIS_DIM       
       INTEGER, INTENT(IN),OPTIONAL :: NP,NS
     END SUBROUTINE BASIS 

     SUBROUTINE CHECK_ORDER(STATE,BASIS_DIM,INFO)
       USE LATTICE
       IMPLICIT NONE
       INTEGER, DIMENSION(:,:), INTENT(IN) :: STATE
       INTEGER, INTENT(IN)  :: BASIS_DIM       
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE CHECK_ORDER

     SUBROUTINE HASHING(STATE,TAG,TAG_INDEX,BASIS_DIM,NS)
       USE LATTICE
       IMPLICIT NONE
       INTEGER, DIMENSION(:,:), INTENT(IN)  :: STATE
       INTEGER, DIMENSION(:),   INTENT(OUT) :: TAG,TAG_INDEX
       INTEGER, INTENT(IN),OPTIONAL :: NS
       INTEGER, INTENT(IN)  :: BASIS_DIM
       
     END SUBROUTINE HASHING
     
     SUBROUTINE CHECK_HASHING(TAG,TAG_INDEX,BASIS_DIM,STATE,INFO)
       USE LATTICE
       IMPLICIT NONE
       INTEGER, DIMENSION(:,:),INTENT(IN) :: STATE
       INTEGER, DIMENSION(BASIS_DIM),   INTENT(IN) :: TAG,TAG_INDEX
       !  INTEGER, DIMENSION(N_SITES,BASIS_DIM),INTENT(IN) :: STATE
       INTEGER, INTENT(IN)  :: BASIS_DIM
       INTEGER, INTENT(OUT) :: INFO
     END SUBROUTINE CHECK_HASHING

     SUBROUTINE HOPPING_TERM(STATE,TAG,TAG_INDEX,H,INFO)       
       USE LATTICE
       IMPLICIT NONE
       INTEGER, DIMENSION(:,:), INTENT(IN)           :: STATE
       INTEGER, DIMENSION(:)  , INTENT(IN)           :: TAG, TAG_INDEX
       INTEGER,                 INTENT(OUT)      :: INFO
       COMPLEX*16, DIMENSION(:,:), INTENT(INOUT) :: H
     END SUBROUTINE HOPPING_TERM

     SUBROUTINE HOPPING_TERM2D(STATE,TAG,TAG_INDEX,H,INFO)       
       USE LATTICE
       IMPLICIT NONE
       INTEGER, DIMENSION(:,:), INTENT(IN)           :: STATE
       INTEGER, DIMENSION(:)  , INTENT(IN)           :: TAG, TAG_INDEX
       INTEGER,                 INTENT(OUT)      :: INFO
       COMPLEX*16, DIMENSION(:,:), INTENT(INOUT) :: H
     END SUBROUTINE HOPPING_TERM2D

     SUBROUTINE LAPACK_FULLEIGENVALUES(H,N,W_SPACE,INFO)
       INTEGER,                    INTENT(IN) :: N
       COMPLEX*16, DIMENSION(:,:), INTENT(INOUT) :: H  
       DOUBLE PRECISION, DIMENSION(:), INTENT(IN) :: W_SPACE
       INTEGER,                    INTENT(OUT):: INFO
     END SUBROUTINE LAPACK_FULLEIGENVALUES
     SUBROUTINE LAPACK_ZGEEV(H,N,W_SPACE,INFO) 
      IMPLICIT NONE
      INTEGER,                        INTENT(IN)    :: N
      COMPLEX*16, DIMENSION(:,:),     INTENT(INOUT) :: H
      COMPLEX*16, DIMENSION(:),       INTENT(OUT)   :: W_SPACE
      INTEGER,                        INTENT(OUT)   :: INFO
     END SUBROUTINE LAPACK_ZGEEV

     SUBROUTINE NEWTON_SEARCHING(elto,array,array_index,elto_index,array_size,INFO)       
       IMPLICIT NONE
       INTEGER,                        INTENT(IN)          :: elto,array_size
       INTEGER, DIMENSION(array_size), INTENT(IN)          :: array
       INTEGER, DIMENSION(:),          INTENT(IN),OPTIONAL :: array_index
       INTEGER,                        INTENT(OUT)         :: elto_index,INFO      
     END SUBROUTINE NEWTON_SEARCHING

  END INTERFACE
END MODULE INTERFACE

MODULE INTERFACE_MAP
  IMPLICIT NONE
  INTERFACE
     SUBROUTINE STATEtoPARTITIONmap(STATE,TAG,TAG_INDEX,SITEMAP_A,SITEMAP_B,C,BASIS_DIM_A,BASIS_DIM_B,INFO)   
        IMPLICIT NONE
       INTEGER, DIMENSION(:,:), INTENT(IN)  :: STATE
       INTEGER, DIMENSION(:),   INTENT(IN)  :: SITEMAP_A, SITEMAP_B,TAG,TAG_INDEX
       INTEGER, DIMENSION(:,:), INTENT(OUT) :: C
       INTEGER, DIMENSION(:),   INTENT(INOUT) :: BASIS_DIM_A,BASIS_DIM_B
       INTEGER,                 INTENT(OUT)   :: INFO
     END SUBROUTINE STATEtoPARTITIONmap

  END INTERFACE
END MODULE INTERFACE_MAP


MODULE INTERFACE_FLOQUETSPECTRUM
  IMPLICIT NONE
  INTERFACE
    SUBROUTINE FLOQUET_BOSE_HUBBARD_SUB(q_,U_T,U_FTY, EIGENVALUES_H,INFO)
      IMPLICIT NONE
      COMPLEX*16, DIMENSION(:,:),INTENT(OUT):: U_T
      COMPLEX*16, DIMENSION(:), INTENT(OUT) :: U_FTY
      DOUBLE PRECISION, DIMENSION(:),INTENT(OUT):: EIGENVALUES_H
      INTEGER, INTENT(IN) :: q_
      INTEGER, INTENT(INOUT) :: INFO
    END SUBROUTINE FLOQUET_BOSE_HUBBARD_SUB
  END INTERFACE
END MODULE INTERFACE_FLOQUETSPECTRUM