MODULE TASKS
IMPLICIT NONE
INTEGER, PARAMETER :: FLOQUET_SPECTRUM  = 0
INTEGER, PARAMETER :: ENTANGLEMENT_SPECTRUM = 0
END MODULE TASKS


MODULE physical_constants
  IMPLICIT NONE
  DOUBLE PRECISION, PARAMETER :: e       = 1.602176462E-19
  DOUBLE PRECISION, PARAMETER :: hbar    = 1.054E-34
  DOUBLE PRECISION, PARAMETER :: mu_B    = 9.2740154E-24
  DOUBLE PRECISION, PARAMETER :: k_B     = 1.38E-23
  DOUBLE PRECISION, PARAMETER :: pi      = 3.1415926
  DOUBLE PRECISION, PARAMETER :: mu_cero = 12.566370614E-7
  DOUBLE PRECISION, PARAMETER :: epsilon_cero = 8.854187817E-12 
  DOUBLE PRECISION, PARAMETER :: amu     = 1.660538921E-27
  DOUBLE PRECISION, PARAMETER :: g_t     = 9.8
  DOUBLE PRECISION, PARAMETER :: SB_ct   = 5.6704E-8
END MODULE physical_constants


MODULE LATTICE
  IMPLICIT NONE
  INTEGER, PARAMETER :: N_SITES   = 3!46080
  INTEGER, PARAMETER :: N_SITES_X = 3!480
  INTEGER, PARAMETER :: N_SITES_Y = 1!96
  INTEGER, PARAMETER :: N_PARTICLES = 6
  INTEGER, PARAMETER :: HASH_SLOPE = 517
  INTEGER, PARAMETER :: HASH_SHIFT = 3!51459
  DOUBLE PRECISION, PARAMETER :: alpha = -1.0/3.0
END MODULE LATTICE

MODULE SUBLATTICE
  IMPLICIT NONE
  INTEGER, PARAMETER :: N_SITES_X_A = 8
  INTEGER, PARAMETER :: N_SITES_Y_A = 32

  INTEGER, PARAMETER :: N_SITES_X_B = 8
  INTEGER, PARAMETER :: N_SITES_Y_B = 32

  INTEGER            :: N_SITES_A  =  N_SITES_X_A*N_SITES_Y_A
END MODULE SUBLATTICE
 
MODULE INTERACTION
  IMPLICIT NONE
  DOUBLE PRECISION, PARAMETER :: J_c = 1.0
  DOUBLE PRECISION, PARAMETER :: J_X = 1.0 ! next-neighbour coupling
  DOUBLE PRECISION, PARAMETER :: J_Y = 1.0
END MODULE INTERACTION

MODULE TIME_DEPENDENT
  USE physical_constants
 
  !A  
  !DOUBLE PRECISION, PARAMETER :: T   =  5.0*pi/6.0
  !B  
  DOUBLE PRECISION, PARAMETER :: T   =  4.0*pi/3.0
  !C  
  !DOUBLE PRECISION, PARAMETER :: T   = 23.0*pi/15.0
  !D  
  !DOUBLE PRECISION, PARAMETER :: T   = 11.0*pi/6.0

  DOUBLE PRECISION, PARAMETER :: tau = pi/3

END MODULE TIME_DEPENDENT


MODULE MATRIX_AUX
 TYPE :: C_matrix      ! Coherent Field in real space
   COMPLEX*16, DIMENSION(:,:), allocatable :: C
 END TYPE C_matrix
END MODULE MATRIX_AUX


MODULE STATE_OBJ
 USE  LATTICE
 TYPE :: STATE      ! State
   INTEGER :: TAG   ! state tag
   INTEGER, DIMENSION(N_PARTICLES) :: site ! where there are particles
   INTEGER, DIMENSION(N_PARTICLES) :: occupation ! number of particles in site
   INTEGER, DIMENSION(N_PARTICLES) :: n
   INTEGER, DIMENSION(N_PARTICLES) :: m   ! coordinates (n,m) == (x,y)
 END TYPE STATE
END MODULE 
